name: CI Build
     
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore Chorn.AzureDevOpsNugetRefresher.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore Chorn.AzureDevOpsNugetRefresher.csproj
    - name: Package
      run: dotnet publish --no-restore --no-build --configuration Release --verbosity normal -o Release/win-x64 Chorn.AzureDevOpsNugetRefresher.csproj
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: AzureDevopsNugetRefresherRelease
        path: Release/win-x64